name: pokemony
description: A new Flutter project for Pokemons.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  dio: ^4.0.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_storage: ^2.0.3
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  pull_to_refresh: ^2.0.0
  double_back_to_close: ^2.0.0
  loading_overlay: ^0.3.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  get: ^4.6.5
  circular_bottom_navigation: ^2.3.0
  molten_navigationbar_flutter: ^1.0.1
  cached_network_image: ^3.2.3
  palette_generator: ^0.3.3+2
  badges: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/